
<?php $__env->startSection('content'); ?>
<div class="landing-progress" aria-hidden="true"><span></span></div>
<div class="landing-page" id="landing-top">
<section class="hero">
<div class="container hero-grid">
<div class="hero-copy"><p class="eyebrow"><span class="little-line"></span> KEBAIKAN DIMULAI DARI KEPEDULIAN</p>
<h1>Ulurkan kebaikan.<br>Tumbuhkan <em>harapan.</em></h1>
<p class="hero-description">Bersama Panti Asuhan NU An-Nuur 2 Kota Kediri, hadirkan perhatian dan dukungan untuk masa depan yang lebih baik.</p>
<div class="hero-actions"><a class="button" href="<?php echo e(route('submission.form','donasi')); ?>">Mulai berbagi <svg class="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></a><a class="button outline" href="<?php echo e(route('page','profil')); ?>">Kenali panti kami</a></div>
<div class="hero-note"><span class="note-icon" aria-hidden="true"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/></svg></span><p>Kebaikan tidak harus besar.<br><strong>Setiap niat baik punya arti.</strong></p></div>
</div>
<div class="hero-art" aria-label="Ilustrasi rumah dan tumbuhan sebagai simbol tempat tumbuh bersama">
<div class="art-sun"></div><div class="art-orbit"></div><div class="art-arch"><span class="arch-star" aria-hidden="true"><svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2l2.4 7.4H22l-6 4.6 2.3 7.2-6.3-4.6-6.3 4.6 2.3-7.2-6-4.6h7.6z"/></svg></span><div class="house-roof"></div><div class="house"><div class="house-window"></div><div class="house-door"></div></div><div class="art-ground"></div><div class="plant plant-left"><i></i><b></b><span></span></div><div class="plant plant-right"><i></i><b></b><span></span></div></div>
<div class="art-label"><span class="label-icon" aria-hidden="true"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/></svg></span><div><strong>Rumah untuk tumbuh</strong><small>Dirawat dengan kasih dan kepedulian</small></div></div>
<span class="art-caption">AN-NUUR 2 · KOTA KEDIRI</span>
</div></div></section>
<nav class="landing-jump container" aria-label="Jelajahi beranda"><span>Jelajahi</span><a href="#panduan-berbagi">Cara berbagi</a><a href="#kebutuhan-beranda">Kebutuhan panti</a><a href="#cerita-beranda">Kegiatan</a><a href="#pertanyaan">Tanya jawab</a></nav>
<section class="ways-section"><div class="container ways-grid">
<a href="<?php echo e(route('submission.form','donasi')); ?>" class="way"><span class="way-icon" aria-hidden="true"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></span><div><h2>Donasi uang</h2><p>Berbagi mulai dari Rp5.000</p></div><span class="way-arrow"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></span></a>
<a href="<?php echo e(route('submission.form','bantuan')); ?>" class="way"><span class="way-icon" aria-hidden="true"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg></span><div><h2>Bantuan barang</h2><p>Dukung kebutuhan sehari-hari</p></div><span class="way-arrow"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></span></a>
<a href="<?php echo e(route('submission.form','kunjungan')); ?>" class="way"><span class="way-icon" aria-hidden="true"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"/></svg></span><div><h2>Datang berkunjung</h2><p>Jalin silaturahmi bersama kami</p></div><span class="way-arrow"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></span></a>
</div></section>
<section id="kebutuhan-beranda" class="section container"><div class="section-heading"><div><p class="eyebrow">BERSAMA MEMENUHI KEBUTUHAN</p><h2>Bantuan yang berarti.</h2></div><a class="text-link" href="<?php echo e(route('page','kebutuhan')); ?>">Semua kebutuhan <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></a></div>
<div class="card-grid"><?php $__empty_1 = true; $__currentLoopData = $needs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?> <?php echo $__env->make('public.partials.need', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
<div class="empty-state wide"><span class="empty-icon" aria-hidden="true"><svg class="w-10 h-10 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"/></svg></span><h3>Kebutuhan akan diperbarui di sini</h3><p>Pengurus sedang menyiapkan informasi kebutuhan panti. Anda tetap dapat berbagi melalui donasi atau bantuan barang.</p><a class="text-link" href="<?php echo e(route('submission.form','bantuan')); ?>">Ajukan bantuan barang <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></a></div>
<?php endif; ?></div></section>
<?php echo $__env->make('public.partials.giving-guide', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="about-band"><div class="container about-grid"><p class="eyebrow">MENGENAL AN-NUUR 2</p><div><h2>Tempat bertumbuh,<br>ruang untuk berharap.</h2><p><?php echo e(\App\Models\Setting::read('tentang') ?: 'Kenali Panti Asuhan NU An-Nuur 2 Kota Kediri dan ikuti kegiatan serta informasi yang dipublikasikan oleh pengurus.'); ?></p><a class="text-link" href="<?php echo e(route('page','profil')); ?>">Tentang panti kami <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></a></div>
<?php if(\App\Models\Setting::read('penerima_manfaat') !== null): ?><div class="beneficiary"><strong><?php echo e(\App\Models\Setting::read('penerima_manfaat')); ?></strong><span>Penerima manfaat</span><small><?php echo e(\App\Models\Setting::read('periode_statistik')); ?></small></div><?php endif; ?></div></section>
<section id="cerita-beranda" class="section container"><div class="section-heading"><div><p class="eyebrow">CERITA DARI RUMAH KAMI</p><h2>Kegiatan & kebersamaan.</h2></div><a class="text-link" href="<?php echo e(route('page','kegiatan')); ?>">Semua kegiatan <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></a></div>
<div class="card-grid"><?php $__empty_1 = true; $__currentLoopData = $activities; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?> <?php echo $__env->make('public.partials.article-card',['page'=>'kegiatan'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?> <div class="empty-state wide"><h3>Menanti cerita kebersamaan</h3><p>Kegiatan yang dipublikasikan pengurus akan tampil di sini.</p></div> <?php endif; ?></div></section>
<section class="container visit-banner"><div><p class="eyebrow">PINTU KAMI TERBUKA</p><h2>Mari hadir dan berbagi cerita.</h2><p>Rencanakan kunjungan Anda. Pengurus akan membantu mengatur jadwal.</p></div><a class="button light" href="<?php echo e(route('submission.form','kunjungan')); ?>">Ajukan kunjungan <svg class="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></a></section>
<?php echo $__env->make('public.partials.home-faq', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<button class="back-to-top" type="button" aria-label="Kembali ke atas" hidden><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 12 6-6 6 6M12 6v14"/></svg><span>Ke atas</span></button>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.public', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\apps\laragon\www\projectTA\resources\views/public/home.blade.php ENDPATH**/ ?>