
<?php $__env->startSection('title','Ringkasan hari ini'); ?>
<?php $__env->startSection('content'); ?>
<p class="mb-6">Selamat datang, <?php echo e(auth()->user()->name); ?>. Berikut perkembangan pengelolaan panti.</p>
<?php if($followUp = \App\Models\Setting::read('tindak_lanjut')): ?><section class="card mb-6"><h2>Perlu dilengkapi</h2><p class="prose-text"><?php echo e($followUp); ?></p><a class="text-link" href="<?php echo e(route('admin.settings')); ?>#profil">Perbarui catatan tindak lanjut</a></section><?php endif; ?>
<?php if($unknownFees): ?><div class="notice"><?php echo e($unknownFees); ?> donasi berhasil belum memiliki informasi biaya. Total bersih hanya menghitung transaksi yang biayanya sudah tercatat.</div><?php endif; ?>
<div class="stats-grid"><?php $__currentLoopData = $stats; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card stat-card"><p><?php echo e($label); ?></p><strong><?php echo e($value); ?></strong></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<div class="dashboard-grid mt-6"><section class="card"><h2>Donasi bersih bulanan</h2><p class="help-text">Enam bulan terakhir · biaya simulasi mengikuti konfigurasi sandbox</p><div class="chart-wrap"><canvas id="donation-chart" data-chart="<?php echo e($chart->toJson()); ?>" aria-label="Grafik donasi bulanan" role="img"></canvas></div></section><section class="card"><h2>Menunggu persetujuan</h2><?php $__empty_1 = true; $__currentLoopData = $visits; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a class="detail-row" href="<?php echo e(route('admin.transaction.show',['kunjungan',$v->id])); ?>"><div><strong><?php echo e($v->nama); ?></strong><small class="block"><?php echo e($v->tanggal); ?> · <?php echo e($v->peserta); ?> peserta</small></div><span><svg class="w-4 h-4 text-emerald-800" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="mt-5">Tidak ada pengajuan kunjungan yang menunggu.</p><?php endif; ?></section></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\apps\laragon\www\projectTA\resources\views/admin/dashboard.blade.php ENDPATH**/ ?>